### ISSUE TITLE
Error:'<=' not supported between instances of 'NoneType' and 'int'

### ISSUE THREAD

**Issue by Keinamvy** [xroix/MCBE-Win10-FOV-Changer#141]
crash_log.txt:
----------------------------------------[20.01.2022 - 07:50:49]----------------------------------------
[07:48:55] + Root Thread
[07:48:55] + ProcessingThread
[07:48:55] + System Tray
[07:48:55] + Storage
[07:48:55] + Network
[07:48:55] + Gateway
[07:48:55] + Discord
[07:48:56] + Root Gui
[07:48:57] > Rendered Settings!
[07:49:10] > Attached to Minecraft!
[07:49:10] > Found MC Version '1.18.203.0'
[07:49:10] > Saved version doesn't match!
[07:49:10] > New feature offsets are needed!
[07:49:10] > Getting features for '1182030'
[07:49:11] > Feature request number 0
[07:49:11] > Saved new features and version
[07:49:11] + Found 0. address for FOV [0x26c93ee62d8]!
[07:49:11] + Found 0. address for Hide Hand [0x26c9295a570]!
[07:49:11] + Found 0. address for Sensitivity [0x26c93e06f94]!
[07:49:11] + Found 0. address for Discord [0x0]!
[07:49:11] + Found 1. address for Discord [0x26ca6841850]!
[07:49:30] > Saved new values! [{'show_server': 1, 'show_version': 1}]
[07:49:32] > Saved new values! [{'before': '40', 'after': '16.0'}]
[07:49:36] > Saved new values! [{'before': '40', 'after': '16.0'}]
[07:49:44] > Saved new values! [{'before': '0', 'after': '1'}]
[07:49:49] > Saved new values! [{'before': '110', 'after': '30.0'}]
[07:49:50] > Detached from Minecraft!
[07:49:54] > Attached to Minecraft!
[07:49:54] > Found MC Version '1.18.203.0'
[07:49:54] > Saved version ist correct!
[07:49:54] + Found 0. address for FOV [0x26c93ee62d8]!
[07:49:54] + Found 0. address for Hide Hand [0x26c9295a570]!
[07:49:54] + Found 0. address for Sensitivity [0x26c93e06f94]!
[07:49:54] + Found 0. address for Discord [0x0]!
[07:49:54] + Found 1. address for Discord [0x26ca6841850]!

Traceback (most recent call last):
  File "src\processing\listener.py", line 76, in inner
  File "src\processing\listener.py", line 38, in unctrl
TypeError: '<=' not supported between instances of 'NoneType' and 'int'

**Comment by Keinamvy** [comment]
Nah, I fixed it by uninstall Python 3 on my computer. I have did some searching on stackoverflow so I fixed it myseft. The problem just randomly happend.

**Comment by xroix** [comment]
I guess I will close this issue then.
If it somehow comes back or if someone else encounters the same problem, just comment on this thread again.
